name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_COMMITTER_NAME: "github-actions[bot]"
      GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      GIT_AUTHOR_NAME: "github-actions[bot]"
      GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: '21'
          cache: gradle

      - run: chmod +x gradlew

      - run: ./gradlew applyAllPatches --stacktrace --no-daemon

      - run: ./gradlew createMojmapPaperclipJar --stacktrace --no-daemon
